---
- name: Create Resource Group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ resource_group_location }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
  # delegate_to: localhost

- name: Trigger AKS Cluster creation handler
  import_tasks: ../handlers/main.yml
  notify: Create AKS Cluster
